import { ethers } from 'hardhat';

//random eth address generated by the vanity website
async function main() {
  const ExamController = await ethers.getContractFactory('ExamController');
  const examController = await ExamController.deploy();

  await examController.deployed();
  console.log(examController.address);
}

// We recommend this pattern to be able to use async/await everywhere
// and properly handle errors.
main().catch(error => {
  console.error(error);
  process.exitCode = 1;
});
