import { ethers } from 'hardhat';

export const EXAM_NAME = 'EXAM_NAME';
export const EXAM_SYMBOL = 'EXS';
//random eth address generated by the vanity website
async function main() {
  const Exam = await ethers.getContractFactory('Exam');
  const exam = await Exam.deploy(
    EXAM_NAME,
    EXAM_SYMBOL,
    '0x86a74F972A4e5f7ba795F80fD97E62151616406E',
    '0x86a74F972A4e5f7ba795F80fD97E62151616406E'
  );

  await exam.deployed();
  await exam.makeNFT('0x86a74f972a4e5f7ba795f80fd97e62151616406e', 88);
}

// We recommend this pattern to be able to use async/await everywhere
// and properly handle errors.
main().catch(error => {
  console.error(error);
  process.exitCode = 1;
});
