export const EXAM_NAME = 'EXAM_NAME';
export const EXAM_SYMBOL = 'EXS';
//random eth address generated by the vanity website
export const EXAM_ADDRESS = '0x3f6aAE044256333cC57EBD78A79B8D5f887D2548';
export const EXAM_SCORE = 88;
export const BACKEND_ADDRESS = '0x86a74F972A4e5f7ba795F80fD97E62151616406E';
